CREATE TABLE "Certificate" (
  "id" VARCHAR(255) PRIMARY KEY NOT NULL,
  "fullName" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "courseName" VARCHAR(255) NOT NULL,
  "duration" VARCHAR(255) NOT NULL,
  "issueDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
